-- Initial seed data for development environment
-- This file contains initial data that can be safely loaded during development

-- Insert categories (expense categories)
INSERT INTO categories (name) VALUES
('accommodation'),
('transportation'),
('food'),
('shopping'),
('entertainment'),
('sightseeing'),
('activities'),
('miscellaneous');

-- Insert travel types
INSERT INTO travel_types (name) VALUES
('solo'),
('couple'),
('family'),
('friends'),
('business'),
('group tour'),
('backpacking'),
('luxury');

-- Insert positions (occupations)
INSERT INTO positions (name) VALUES
('student'),
('office worker'),
('freelancer'),
('entrepreneur'),
('teacher'),
('engineer'),
('designer'),
('consultant'),
('researcher'),
('artist'),
('writer'),
('photographer'),
('retired'),
('other');

-- Insert expense card statuses
INSERT INTO expense_card_statuses (name) VALUES
('public'),
('editing');

-- Insert cities data
INSERT INTO cities (name, country) VALUES
('tokyo', 'japan'),
('osaka', 'japan'),
('kyoto', 'japan'),
('sapporo', 'japan'),
('fukuoka', 'japan'),
('okinawa', 'japan'),
('nagoya', 'japan'),
('hiroshima', 'japan'),
('sendai', 'japan'),
('yokohama', 'japan'),
('kobe', 'japan'),
('kanazawa', 'japan'),
('hakodate', 'japan'),
('nara', 'japan'),
('karuizawa', 'japan'),
('chiba', 'japan'),
('saitama', 'japan'),
('shizuoka', 'japan'),
('niigata', 'japan'),
('kumamoto', 'japan'),
('kagoshima', 'japan'),
('matsuyama', 'japan'),
('takayama', 'japan'),
('ishigaki', 'japan'),
('beppu', 'japan'),

('seoul', 'south korea'),
('busan', 'south korea'),
('jeju', 'south korea'),
('incheon', 'south korea'),
('gwangju', 'south korea'),
('daejeon', 'south korea'),
('daegu', 'south korea'),
('taipei', 'taiwan'),
('kaohsiung', 'taiwan'),
('taichung', 'taiwan'),
('tainan', 'taiwan'),
('hualien', 'taiwan'),
('bangkok', 'thailand'),
('chiang mai', 'thailand'),
('phuket', 'thailand'),
('pattaya', 'thailand'),
('koh samui', 'thailand'),
('singapore', 'singapore'),
('hong kong', null),
('macau', null),
('shanghai', 'china'),
('beijing', 'china'),
('guangzhou', 'china'),
('chengdu', 'china'),
('chongqing', 'china'),
('xian', 'china'),
('hangzhou', 'china'),
('shenzhen', 'china'),
('qingdao', 'china'),
('nanjing', 'china'),
('ho chi minh city', 'vietnam'),
('hanoi', 'vietnam'),
('da nang', 'vietnam'),
('hoi an', 'vietnam'),
('hue', 'vietnam'),
('phu quoc', 'vietnam'),
('kuala lumpur', 'malaysia'),
('penang', 'malaysia'),
('kota kinabalu', 'malaysia'),
('langkawi', 'malaysia'),
('bali', 'indonesia'),
('jakarta', 'indonesia'),
('yogyakarta', 'indonesia'),
('bandung', 'indonesia'),
('surabaya', 'indonesia'),
('dubai', 'united arab emirates'),
('abu dhabi', 'united arab emirates'),
('doha', 'qatar'),
('riyadh', 'saudi arabia'),
('jeddah', 'saudi arabia'),
('muscat', 'oman'),
('manama', 'bahrain'),
('kuwait city', 'kuwait'),
('delhi', 'india'),
('mumbai', 'india'),
('bangalore', 'india'),
('chennai', 'india'),
('kolkata', 'india'),
('jaipur', 'india'),
('agra', 'india'),
('goa', 'india'),
('siem reap', 'cambodia'),
('phnom penh', 'cambodia'),
('colombo', 'sri lanka'),
('malé', 'maldives'),
('kathmandu', 'nepal'),
('thimphu', 'bhutan'),
('dhaka', 'bangladesh'),
('yangon', 'myanmar'),
('vientiane', 'laos'),
('ulaanbaatar', 'mongolia'),
('baku', 'azerbaijan'),
('tbilisi', 'georgia'),
('yerevan', 'armenia'),
('nur-sultan', 'kazakhstan'),
('tashkent', 'uzbekistan'),

('paris', 'france'),
('nice', 'france'),
('marseille', 'france'),
('lyon', 'france'),
('bordeaux', 'france'),
('strasbourg', 'france'),
('cannes', 'france'),
('rome', 'italy'),
('florence', 'italy'),
('venice', 'italy'),
('milan', 'italy'),
('naples', 'italy'),
('bologna', 'italy'),
('turin', 'italy'),
('london', 'united kingdom'),
('edinburgh', 'united kingdom'),
('manchester', 'united kingdom'),
('liverpool', 'united kingdom'),
('dublin', 'ireland'),
('galway', 'ireland'),
('barcelona', 'spain'),
('madrid', 'spain'),
('seville', 'spain'),
('valencia', 'spain'),
('granada', 'spain'),
('malaga', 'spain'),
('palma de mallorca', 'spain'),
('amsterdam', 'netherlands'),
('rotterdam', 'netherlands'),
('utrecht', 'netherlands'),
('berlin', 'germany'),
('munich', 'germany'),
('frankfurt', 'germany'),
('hamburg', 'germany'),
('cologne', 'germany'),
('dusseldorf', 'germany'),
('prague', 'czech republic'),
('brno', 'czech republic'),
('krakow', 'poland'),
('warsaw', 'poland'),
('wroclaw', 'poland'),
('vienna', 'austria'),
('salzburg', 'austria'),
('budapest', 'hungary'),
('lisbon', 'portugal'),
('porto', 'portugal'),
('zagreb', 'croatia'),
('dubrovnik', 'croatia'),
('split', 'croatia'),
('ljubljana', 'slovenia'),
('belgrade', 'serbia'),
('sarajevo', 'bosnia and herzegovina'),
('skopje', 'north macedonia'),
('tirana', 'albania'),
('sofia', 'bulgaria'),
('bucharest', 'romania'),
('kiev', 'ukraine'),
('odessa', 'ukraine'),
('moscow', 'russia'),
('saint petersburg', 'russia'),
('helsinki', 'finland'),
('stockholm', 'sweden'),
('gothenburg', 'sweden'),
('copenhagen', 'denmark'),
('oslo', 'norway'),
('bergen', 'norway'),
('reykjavik', 'iceland'),
('athens', 'greece'),
('santorini', 'greece'),
('mykonos', 'greece'),
('thessaloniki', 'greece'),
('istanbul', 'turkey'),
('ankara', 'turkey'),
('izmir', 'turkey'),
('cappadocia', 'turkey'),
('zurich', 'switzerland'),
('geneva', 'switzerland'),
('bern', 'switzerland'),
('lucerne', 'switzerland'),
('brussels', 'belgium'),
('bruges', 'belgium'),
('antwerp', 'belgium'),
('luxembourg city', 'luxembourg'),
('monaco', 'monaco'),
('vatican city', 'vatican city'),
('valletta', 'malta'),
('nicosia', 'cyprus'),
('tallinn', 'estonia'),
('riga', 'latvia'),
('vilnius', 'lithuania'),
('minsk', 'belarus'),
('chișinău', 'moldova'),
('podgorica', 'montenegro'),
('prishtina', 'kosovo'),
('sydney', 'australia'),
('melbourne', 'australia'),
('brisbane', 'australia'),
('perth', 'australia'),
('adelaide', 'australia'),
('gold coast', 'australia'),
('cairns', 'australia'),
('hobart', 'australia'),
('canberra', 'australia'),
('auckland', 'new zealand'),
('queenstown', 'new zealand'),
('wellington', 'new zealand'),
('christchurch', 'new zealand'),
('suva', 'fiji'),
('papeete', 'french polynesia'),
('apia', 'samoa'),
('port vila', 'vanuatu'),
('nadi', 'fiji'),

('new york', 'united states'),
('los angeles', 'united states'),
('san francisco', 'united states'),
('las vegas', 'united states'),
('miami', 'united states'),
('orlando', 'united states'),
('chicago', 'united states'),
('boston', 'united states'),
('seattle', 'united states'),
('honolulu', 'united states'),
('washington d.c.', 'united states'),
('houston', 'united states'),
('dallas', 'united states'),
('philadelphia', 'united states'),
('atlanta', 'united states'),
('denver', 'united states'),
('phoenix', 'united states'),
('san diego', 'united states'),
('new orleans', 'united states'),
('nashville', 'united states'),
('charleston', 'united states'),
('salt lake city', 'united states'),
('portland', 'united states'),
('san antonio', 'united states'),
('austin', 'united states'),
('columbus', 'united states'),
('indianapolis', 'united states'),
('detroit', 'united states'),
('st. louis', 'united states'),
('minneapolis', 'united states'),
('baltimore', 'united states'),
('vancouver', 'canada'),
('toronto', 'canada'),
('montreal', 'canada'),
('calgary', 'canada'),
('quebec city', 'canada'),
('ottawa', 'canada'),
('halifax', 'canada'),
('mexico city', 'mexico'),
('cancun', 'mexico'),
('puerto vallarta', 'mexico'),
('guadalajara', 'mexico'),
('riviera maya', 'mexico'),
('havana', 'cuba'),
('santo domingo', 'dominican republic'),
('san juan', 'puerto rico'),
('kingston', 'jamaica'),
('nassau', 'bahamas'),
('st. barth', 'france'),
('castries', 'saint lucia'),
('bridgetown', 'barbados'),
('port of spain', 'trinidad and tobago'),
('panama city', 'panama'),
('san jose', 'costa rica'),
('belize city', 'belize'),
('guatemala city', 'guatemala'),
('san salvador', 'el salvador'),
('tegucigalpa', 'honduras'),
('managua', 'nicaragua'),
('bogota', 'colombia'),
('cartagena', 'colombia'),
('medellin', 'colombia'),
('lima', 'peru'),
('cusco', 'peru'),
('machu picchu', 'peru'),
('quito', 'ecuador'),
('galapagos islands', 'ecuador'),
('santiago', 'chile'),
('rio de janeiro', 'brazil'),
('sao paulo', 'brazil'),
('brasilia', 'brazil'),
('buenos aires', 'argentina'),
('bariloche', 'argentina'),
('montevideo', 'uruguay'),
('asuncion', 'paraguay'),
('la paz', 'bolivia'),

('cairo', 'egypt'),
('luxor', 'egypt'),
('sharm el sheikh', 'egypt'),
('marrakech', 'morocco'),
('casablanca', 'morocco'),
('fes', 'morocco'),
('cape town', 'south africa'),
('johannesburg', 'south africa'),
('nairobi', 'kenya'),
('dar es salaam', 'tanzania'),
('zanzibar', 'tanzania'),
('addis ababa', 'ethiopia'),
('lagos', 'nigeria'),
('accra', 'ghana'),
('dakar', 'senegal'),
('tunis', 'tunisia'),
('algiers', 'algeria'),
('tripoli', 'libya'),
('khartoum', 'sudan'),
('luanda', 'angola'),
('harare', 'zimbabwe'),
('victoria falls', 'zimbabwe'),
('seychelles', 'seychelles'),
('mauritius', 'mauritius'),
('reunion', 'france'),
('gaborone', 'botswana'),
('windhoek', 'namibia'),
('antananarivo', 'madagascar'),

('el aaiún', null),
('jerusalem', null),
('sevastopol', null),
('simferopol', null),
('tskaltubo', 'georgia'),
('sukhumi', null),
('tskhinvali', null),
('north nicosia', null),
('ramallah', 'palestine'),
('gaza city', 'palestine');
