import { CityCard } from "./card/types";

/**
 * Mock data for city cards
 */
export const mockCityCards: CityCard[] = [
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    averageCost: 85.5,
    currency: "USD",
    pinCount: 124,
    contributionCount: 37,
    topPost: {
      id: "tokyo-post-1",
      cost: 72.0,
      startDate: "2024-11-15",
      endDate: "2024-11-22",
      travelType: "Solo",
      position: "Student",
      author: {
        id: "user-1",
        username: "tokyo_wanderer",
        avatarUrl: undefined,
      },
      bookmarkCount: 28,
    },
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    averageCost: 95.2,
    currency: "USD",
    pinCount: 98,
    contributionCount: 24,
    topPost: {
      id: "paris-post-1",
      cost: 88.0,
      startDate: "2024-10-08",
      endDate: "2024-10-15",
      travelType: "Couple",
      position: "Working",
      author: {
        id: "user-2",
        username: "parisien_dreams",
        avatarUrl: undefined,
      },
      bookmarkCount: 35,
    },
  },
  {
    id: "new-york",
    name: "New York",
    country: "United States",
    averageCost: 128.7,
    currency: "USD",
    pinCount: 156,
    contributionCount: 52,
    topPost: {
      id: "ny-post-1",
      cost: 115.0,
      startDate: "2024-09-20",
      endDate: "2024-09-27",
      travelType: "Solo",
      position: "Working",
      author: {
        id: "user-3",
        username: "bigapple_explorer",
        avatarUrl: undefined,
      },
      bookmarkCount: 42,
    },
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    averageCost: 102.3,
    currency: "USD",
    pinCount: 89,
    contributionCount: 31,
    topPost: {
      id: "london-post-1",
      cost: 94.5,
      startDate: "2024-08-12",
      endDate: "2024-08-19",
      travelType: "Family",
      position: "Working",
      author: {
        id: "user-4",
        username: "london_bridge",
        avatarUrl: undefined,
      },
      bookmarkCount: 19,
    },
  },
  {
    id: "seoul",
    name: "Seoul",
    country: "South Korea",
    averageCost: 67.8,
    currency: "USD",
    pinCount: 76,
    contributionCount: 28,
    topPost: {
      id: "seoul-post-1",
      cost: 59.0,
      startDate: "2024-07-03",
      endDate: "2024-07-10",
      travelType: "Solo",
      position: "Student",
      author: {
        id: "user-5",
        username: "seoul_foodie",
        avatarUrl: undefined,
      },
      bookmarkCount: 31,
    },
  },
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    averageCost: 112.4,
    currency: "USD",
    pinCount: 63,
    contributionCount: 19,
    topPost: {
      id: "sydney-post-1",
      cost: 105.0,
      startDate: "2024-06-18",
      endDate: "2024-06-25",
      travelType: "Couple",
      position: "Working",
      author: {
        id: "user-6",
        username: "aussie_adventure",
        avatarUrl: undefined,
      },
      bookmarkCount: 22,
    },
  },
];
