import { CityExpenseData } from "./types";

/**
 * Mock data for expense cards organized by city
 * 6 cities x 6 expense cards each
 */
export const mockCityExpenseData: Record<string, CityExpenseData> = {
  tokyo: {
    cityId: "tokyo",
    cityName: "Tokyo",
    country: "Japan",
    totalCards: 6,
    averageCost: 85.5,
    currency: "USD",
    expenseCards: [
      {
        id: "tokyo-exp-1",
        cityId: "tokyo",
        cityName: "Tokyo",
        country: "Japan",
        title: "Budget Solo Adventure in Tokyo",
        startDate: "2024-11-15",
        endDate: "2024-11-22",
        travelType: "Solo",
        position: "Student",
        participants: "1",
        overallDescription:
          "Amazing week in Tokyo exploring temples, trying street food, and experiencing the vibrant culture. Stayed in budget hostels and used public transport extensively.",
        totalCost: 504,
        currency: "USD",
        dailyCost: 72.0,
        duration: 7,
        bookmarkCount: 28,
        isBookmarked: false,
        author: {
          id: "user-1",
          username: "tokyo_wanderer",
        },
        createdAt: "2024-11-25T10:30:00Z",
        status: "published",
      },
      {
        id: "tokyo-exp-2",
        cityId: "tokyo",
        cityName: "Tokyo",
        country: "Japan",
        title: "Luxury Tokyo Experience",
        startDate: "2024-10-10",
        endDate: "2024-10-15",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "High-end Tokyo experience with luxury hotels, Michelin restaurants, and premium shopping. Perfect honeymoon trip with unforgettable memories.",
        totalCost: 2100,
        currency: "USD",
        dailyCost: 210.0,
        duration: 5,
        bookmarkCount: 15,
        isBookmarked: true,
        author: {
          id: "user-7",
          username: "luxury_traveler",
        },
        createdAt: "2024-10-20T14:15:00Z",
        status: "published",
      },
      {
        id: "tokyo-exp-3",
        cityId: "tokyo",
        cityName: "Tokyo",
        country: "Japan",
        title: "Family Fun in Tokyo",
        startDate: "2024-09-05",
        endDate: "2024-09-12",
        travelType: "Family",
        position: "Working",
        participants: "4",
        overallDescription:
          "Family trip to Tokyo with kids. Visited Tokyo Disneyland, TeamLab, and many kid-friendly attractions. Great balance of fun and culture.",
        totalCost: 2800,
        currency: "USD",
        dailyCost: 100.0,
        duration: 7,
        bookmarkCount: 22,
        isBookmarked: false,
        author: {
          id: "user-8",
          username: "family_explorer",
        },
        createdAt: "2024-09-18T09:45:00Z",
        status: "published",
      },
      {
        id: "tokyo-exp-4",
        cityId: "tokyo",
        cityName: "Tokyo",
        country: "Japan",
        title: "Digital Nomad Tokyo",
        startDate: "2024-08-01",
        endDate: "2024-08-14",
        travelType: "Solo",
        position: "Freelancer",
        participants: "1",
        overallDescription:
          "Two weeks working remotely from Tokyo. Found great coworking spaces, local cafes, and maintained work-life balance while exploring the city.",
        totalCost: 1170,
        currency: "USD",
        dailyCost: 90.0,
        duration: 13,
        bookmarkCount: 35,
        isBookmarked: true,
        author: {
          id: "user-9",
          username: "nomad_coder",
        },
        createdAt: "2024-08-20T16:20:00Z",
        status: "published",
      },
      {
        id: "tokyo-exp-5",
        cityId: "tokyo",
        cityName: "Tokyo",
        country: "Japan",
        title: "Tokyo Food Adventure",
        startDate: "2024-07-20",
        endDate: "2024-07-24",
        travelType: "Friends",
        position: "Student",
        participants: "3",
        overallDescription:
          "Epic food journey through Tokyo with friends. From ramen alleys to sushi counters, we ate our way through the city's incredible culinary scene.",
        totalCost: 600,
        currency: "USD",
        dailyCost: 50.0,
        duration: 4,
        bookmarkCount: 41,
        isBookmarked: false,
        author: {
          id: "user-10",
          username: "tokyo_foodie",
        },
        createdAt: "2024-07-30T11:10:00Z",
        status: "published",
      },
      {
        id: "tokyo-exp-6",
        cityId: "tokyo",
        cityName: "Tokyo",
        country: "Japan",
        title: "Business Trip Tokyo",
        startDate: "2024-06-15",
        endDate: "2024-06-18",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Short business trip to Tokyo with some time for sightseeing. Efficient use of time to experience both work and leisure in this amazing city.",
        totalCost: 480,
        currency: "USD",
        dailyCost: 120.0,
        duration: 4,
        bookmarkCount: 12,
        isBookmarked: false,
        author: {
          id: "user-11",
          username: "business_traveler",
        },
        createdAt: "2024-06-25T13:50:00Z",
        status: "published",
      },
    ],
  },
  paris: {
    cityId: "paris",
    cityName: "Paris",
    country: "France",
    totalCards: 6,
    averageCost: 95.2,
    currency: "USD",
    expenseCards: [
      {
        id: "paris-exp-1",
        cityId: "paris",
        cityName: "Paris",
        country: "France",
        title: "Romantic Paris Getaway",
        startDate: "2024-10-08",
        endDate: "2024-10-15",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Perfect romantic week in Paris. Visited all the iconic landmarks, enjoyed Seine river cruises, and had incredible dinners at charming bistros.",
        totalCost: 1232,
        currency: "USD",
        dailyCost: 88.0,
        duration: 7,
        bookmarkCount: 35,
        isBookmarked: true,
        author: {
          id: "user-2",
          username: "parisien_dreams",
        },
        createdAt: "2024-10-22T15:30:00Z",
        status: "published",
      },
      {
        id: "paris-exp-2",
        cityId: "paris",
        cityName: "Paris",
        country: "France",
        title: "Art Lover's Paris",
        startDate: "2024-09-12",
        endDate: "2024-09-18",
        travelType: "Solo",
        position: "Student",
        participants: "1",
        overallDescription:
          "Museum hopping in Paris! Spent days at the Louvre, Musée d'Orsay, and countless galleries. A dream trip for any art enthusiast.",
        totalCost: 420,
        currency: "USD",
        dailyCost: 70.0,
        duration: 6,
        bookmarkCount: 24,
        isBookmarked: false,
        author: {
          id: "user-12",
          username: "art_student",
        },
        createdAt: "2024-09-25T10:15:00Z",
        status: "published",
      },
      {
        id: "paris-exp-3",
        cityId: "paris",
        cityName: "Paris",
        country: "France",
        title: "Paris Fashion Week Experience",
        startDate: "2024-09-25",
        endDate: "2024-10-01",
        travelType: "Friends",
        position: "Working",
        participants: "2",
        overallDescription:
          "Attended Paris Fashion Week events and explored the fashion districts. Expensive but absolutely worth it for fashion lovers.",
        totalCost: 2100,
        currency: "USD",
        dailyCost: 175.0,
        duration: 6,
        bookmarkCount: 18,
        isBookmarked: true,
        author: {
          id: "user-13",
          username: "fashion_guru",
        },
        createdAt: "2024-10-05T12:40:00Z",
        status: "published",
      },
      {
        id: "paris-exp-4",
        cityId: "paris",
        cityName: "Paris",
        country: "France",
        title: "Budget Backpacker Paris",
        startDate: "2024-08-15",
        endDate: "2024-08-22",
        travelType: "Solo",
        position: "Student",
        participants: "1",
        overallDescription:
          "Backpacking through Paris on a tight budget. Stayed in hostels, cooked own meals, and found free activities. Proof that Paris can be affordable!",
        totalCost: 350,
        currency: "USD",
        dailyCost: 50.0,
        duration: 7,
        bookmarkCount: 42,
        isBookmarked: false,
        author: {
          id: "user-14",
          username: "budget_backpacker",
        },
        createdAt: "2024-08-28T09:20:00Z",
        status: "published",
      },
      {
        id: "paris-exp-5",
        cityId: "paris",
        cityName: "Paris",
        country: "France",
        title: "Family Paris Adventure",
        startDate: "2024-07-10",
        endDate: "2024-07-17",
        travelType: "Family",
        position: "Working",
        participants: "4",
        overallDescription:
          "Amazing family trip to Paris with kids. Disneyland Paris, Eiffel Tower, and many family-friendly activities. Kids loved every moment!",
        totalCost: 2800,
        currency: "USD",
        dailyCost: 100.0,
        duration: 7,
        bookmarkCount: 31,
        isBookmarked: false,
        author: {
          id: "user-15",
          username: "paris_family",
        },
        createdAt: "2024-07-25T14:10:00Z",
        status: "published",
      },
      {
        id: "paris-exp-6",
        cityId: "paris",
        cityName: "Paris",
        country: "France",
        title: "Culinary Tour of Paris",
        startDate: "2024-06-20",
        endDate: "2024-06-25",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Food-focused trip to Paris. Cooking classes, wine tastings, market tours, and meals at amazing restaurants. A gastronomic paradise!",
        totalCost: 1400,
        currency: "USD",
        dailyCost: 140.0,
        duration: 5,
        bookmarkCount: 28,
        isBookmarked: true,
        author: {
          id: "user-16",
          username: "paris_gourmand",
        },
        createdAt: "2024-06-30T16:45:00Z",
        status: "published",
      },
    ],
  },
  "new-york": {
    cityId: "new-york",
    cityName: "New York",
    country: "United States",
    totalCards: 6,
    averageCost: 128.7,
    currency: "USD",
    expenseCards: [
      {
        id: "ny-exp-1",
        cityId: "new-york",
        cityName: "New York",
        country: "United States",
        title: "The Big Apple Solo Adventure",
        startDate: "2024-09-20",
        endDate: "2024-09-27",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Week-long solo exploration of NYC. Broadway shows, world-class museums, Central Park walks, and incredible food diversity. The city that never sleeps!",
        totalCost: 805,
        currency: "USD",
        dailyCost: 115.0,
        duration: 7,
        bookmarkCount: 42,
        isBookmarked: false,
        author: {
          id: "user-3",
          username: "bigapple_explorer",
        },
        createdAt: "2024-10-02T11:20:00Z",
        status: "published",
      },
      {
        id: "ny-exp-2",
        cityId: "new-york",
        cityName: "New York",
        country: "United States",
        title: "NYC Luxury Weekend",
        startDate: "2024-11-01",
        endDate: "2024-11-03",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Luxury weekend in Manhattan. 5-star hotel, fine dining, helicopter tour, and premium shopping. Short but incredibly memorable trip.",
        totalCost: 1200,
        currency: "USD",
        dailyCost: 200.0,
        duration: 3,
        bookmarkCount: 19,
        isBookmarked: true,
        author: {
          id: "user-17",
          username: "nyc_luxury",
        },
        createdAt: "2024-11-10T13:15:00Z",
        status: "published",
      },
      {
        id: "ny-exp-3",
        cityId: "new-york",
        cityName: "New York",
        country: "United States",
        title: "Student's NYC Experience",
        startDate: "2024-08-05",
        endDate: "2024-08-12",
        travelType: "Friends",
        position: "Student",
        participants: "3",
        overallDescription:
          "College friends exploring NYC on a student budget. Free museum days, cheap eats, walking tours, and staying in budget accommodations.",
        totalCost: 1050,
        currency: "USD",
        dailyCost: 50.0,
        duration: 7,
        bookmarkCount: 38,
        isBookmarked: false,
        author: {
          id: "user-18",
          username: "college_trio",
        },
        createdAt: "2024-08-18T10:30:00Z",
        status: "published",
      },
      {
        id: "ny-exp-4",
        cityId: "new-york",
        cityName: "New York",
        country: "United States",
        title: "NYC Business & Leisure",
        startDate: "2024-07-15",
        endDate: "2024-07-20",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Combined business trip with leisure time in NYC. Productive meetings, networking events, and exploring the city's business district and nightlife.",
        totalCost: 750,
        currency: "USD",
        dailyCost: 150.0,
        duration: 5,
        bookmarkCount: 15,
        isBookmarked: false,
        author: {
          id: "user-19",
          username: "business_nyc",
        },
        createdAt: "2024-07-25T15:40:00Z",
        status: "published",
      },
      {
        id: "ny-exp-5",
        cityId: "new-york",
        cityName: "New York",
        country: "United States",
        title: "Family NYC Holiday",
        startDate: "2024-12-20",
        endDate: "2024-12-26",
        travelType: "Family",
        position: "Working",
        participants: "4",
        overallDescription:
          "Magical Christmas in NYC with family. Ice skating, holiday markets, Broadway shows, and seeing the city decorated for the holidays.",
        totalCost: 2400,
        currency: "USD",
        dailyCost: 100.0,
        duration: 6,
        bookmarkCount: 45,
        isBookmarked: true,
        author: {
          id: "user-20",
          username: "nyc_christmas",
        },
        createdAt: "2024-12-30T12:00:00Z",
        status: "published",
      },
      {
        id: "ny-exp-6",
        cityId: "new-york",
        cityName: "New York",
        country: "United States",
        title: "NYC Food Tour Extravaganza",
        startDate: "2024-06-10",
        endDate: "2024-06-14",
        travelType: "Solo",
        position: "Freelancer",
        participants: "1",
        overallDescription:
          "Food-focused trip to NYC. From street vendors to Michelin-starred restaurants, exploring the incredible culinary diversity of the city.",
        totalCost: 600,
        currency: "USD",
        dailyCost: 120.0,
        duration: 5,
        bookmarkCount: 33,
        isBookmarked: false,
        author: {
          id: "user-21",
          username: "nyc_foodie",
        },
        createdAt: "2024-06-20T14:20:00Z",
        status: "published",
      },
    ],
  },
  london: {
    cityId: "london",
    cityName: "London",
    country: "United Kingdom",
    totalCards: 6,
    averageCost: 102.3,
    currency: "USD",
    expenseCards: [
      {
        id: "london-exp-1",
        cityId: "london",
        cityName: "London",
        country: "United Kingdom",
        title: "Royal London Family Trip",
        startDate: "2024-08-12",
        endDate: "2024-08-19",
        travelType: "Family",
        position: "Working",
        participants: "4",
        overallDescription:
          "Amazing family trip exploring royal London. Buckingham Palace, Tower of London, and many historical sites. Kids loved the royal history!",
        totalCost: 2100,
        currency: "USD",
        dailyCost: 94.5,
        duration: 7,
        bookmarkCount: 19,
        isBookmarked: false,
        author: {
          id: "user-4",
          username: "london_bridge",
        },
        createdAt: "2024-08-25T09:45:00Z",
        status: "published",
      },
      {
        id: "london-exp-2",
        cityId: "london",
        cityName: "London",
        country: "United Kingdom",
        title: "London Theater & Culture",
        startDate: "2024-09-15",
        endDate: "2024-09-20",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Culture-rich trip to London focusing on theater, museums, and arts. West End shows every night and world-class museums during the day.",
        totalCost: 1400,
        currency: "USD",
        dailyCost: 140.0,
        duration: 5,
        bookmarkCount: 27,
        isBookmarked: true,
        author: {
          id: "user-22",
          username: "theater_lover",
        },
        createdAt: "2024-09-25T16:10:00Z",
        status: "published",
      },
      {
        id: "london-exp-3",
        cityId: "london",
        cityName: "London",
        country: "United Kingdom",
        title: "Budget London Adventure",
        startDate: "2024-07-08",
        endDate: "2024-07-15",
        travelType: "Solo",
        position: "Student",
        participants: "1",
        overallDescription:
          "Exploring London on a tight student budget. Free museums, parks, markets, and affordable eats. Proved London can be done affordably!",
        totalCost: 420,
        currency: "USD",
        dailyCost: 60.0,
        duration: 7,
        bookmarkCount: 51,
        isBookmarked: false,
        author: {
          id: "user-23",
          username: "london_student",
        },
        createdAt: "2024-07-20T11:30:00Z",
        status: "published",
      },
      {
        id: "london-exp-4",
        cityId: "london",
        cityName: "London",
        country: "United Kingdom",
        title: "London Pub Crawl Weekend",
        startDate: "2024-10-25",
        endDate: "2024-10-28",
        travelType: "Friends",
        position: "Working",
        participants: "4",
        overallDescription:
          "Epic weekend exploring London's pub culture with friends. Historic pubs, craft breweries, and traditional British fare. Cheers!",
        totalCost: 800,
        currency: "USD",
        dailyCost: 50.0,
        duration: 4,
        bookmarkCount: 22,
        isBookmarked: true,
        author: {
          id: "user-24",
          username: "pub_crawler",
        },
        createdAt: "2024-11-01T14:25:00Z",
        status: "published",
      },
      {
        id: "london-exp-5",
        cityId: "london",
        cityName: "London",
        country: "United Kingdom",
        title: "London Business Conference",
        startDate: "2024-06-03",
        endDate: "2024-06-07",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Business conference in London with some sightseeing time. Professional networking and exploring the financial district of London.",
        totalCost: 800,
        currency: "USD",
        dailyCost: 160.0,
        duration: 5,
        bookmarkCount: 8,
        isBookmarked: false,
        author: {
          id: "user-25",
          username: "london_business",
        },
        createdAt: "2024-06-12T10:15:00Z",
        status: "published",
      },
      {
        id: "london-exp-6",
        cityId: "london",
        cityName: "London",
        country: "United Kingdom",
        title: "London Markets & Shopping",
        startDate: "2024-11-15",
        endDate: "2024-11-18",
        travelType: "Friends",
        position: "Working",
        participants: "2",
        overallDescription:
          "Shopping-focused trip to London. Camden Market, Portobello Road, Oxford Street, and vintage shopping. A shopaholic's paradise!",
        totalCost: 1200,
        currency: "USD",
        dailyCost: 150.0,
        duration: 4,
        bookmarkCount: 16,
        isBookmarked: false,
        author: {
          id: "user-26",
          username: "london_shopper",
        },
        createdAt: "2024-11-22T13:40:00Z",
        status: "published",
      },
    ],
  },
  seoul: {
    cityId: "seoul",
    cityName: "Seoul",
    country: "South Korea",
    totalCards: 6,
    averageCost: 67.8,
    currency: "USD",
    expenseCards: [
      {
        id: "seoul-exp-1",
        cityId: "seoul",
        cityName: "Seoul",
        country: "South Korea",
        title: "K-Culture Seoul Experience",
        startDate: "2024-07-03",
        endDate: "2024-07-10",
        travelType: "Solo",
        position: "Student",
        participants: "1",
        overallDescription:
          "Deep dive into Korean culture in Seoul. K-pop experiences, traditional palaces, Korean BBQ, and shopping in Myeongdong. Amazing cultural immersion!",
        totalCost: 413,
        currency: "USD",
        dailyCost: 59.0,
        duration: 7,
        bookmarkCount: 31,
        isBookmarked: false,
        author: {
          id: "user-5",
          username: "seoul_foodie",
        },
        createdAt: "2024-07-15T12:20:00Z",
        status: "published",
      },
      {
        id: "seoul-exp-2",
        cityId: "seoul",
        cityName: "Seoul",
        country: "South Korea",
        title: "Seoul Food Paradise",
        startDate: "2024-08-20",
        endDate: "2024-08-25",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Food lover's dream trip to Seoul. Street food tours, traditional markets, high-end Korean restaurants, and cooking classes. Culinary heaven!",
        totalCost: 700,
        currency: "USD",
        dailyCost: 70.0,
        duration: 5,
        bookmarkCount: 44,
        isBookmarked: true,
        author: {
          id: "user-27",
          username: "korean_food_lover",
        },
        createdAt: "2024-08-30T15:10:00Z",
        status: "published",
      },
      {
        id: "seoul-exp-3",
        cityId: "seoul",
        cityName: "Seoul",
        country: "South Korea",
        title: "Budget Seoul Adventure",
        startDate: "2024-09-10",
        endDate: "2024-09-17",
        travelType: "Friends",
        position: "Student",
        participants: "3",
        overallDescription:
          "Student budget trip to Seoul with friends. Hostels, street food, free palace tours, and hiking. Affordable way to experience Seoul!",
        totalCost: 630,
        currency: "USD",
        dailyCost: 30.0,
        duration: 7,
        bookmarkCount: 56,
        isBookmarked: false,
        author: {
          id: "user-28",
          username: "seoul_students",
        },
        createdAt: "2024-09-22T10:45:00Z",
        status: "published",
      },
      {
        id: "seoul-exp-4",
        cityId: "seoul",
        cityName: "Seoul",
        country: "South Korea",
        title: "Seoul Tech & Innovation Tour",
        startDate: "2024-06-15",
        endDate: "2024-06-20",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Tech-focused trip to Seoul. Visiting tech companies, innovation centers, and experiencing Seoul's digital transformation. Fascinating insights!",
        totalCost: 600,
        currency: "USD",
        dailyCost: 100.0,
        duration: 6,
        bookmarkCount: 18,
        isBookmarked: true,
        author: {
          id: "user-29",
          username: "tech_explorer",
        },
        createdAt: "2024-06-25T14:30:00Z",
        status: "published",
      },
      {
        id: "seoul-exp-5",
        cityId: "seoul",
        cityName: "Seoul",
        country: "South Korea",
        title: "Seoul Spa & Wellness Retreat",
        startDate: "2024-10-12",
        endDate: "2024-10-16",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Wellness-focused trip to Seoul. Jjimjilbangs, spa treatments, healthy Korean cuisine, and meditation temples. Perfect relaxation getaway!",
        totalCost: 500,
        currency: "USD",
        dailyCost: 125.0,
        duration: 4,
        bookmarkCount: 29,
        isBookmarked: false,
        author: {
          id: "user-30",
          username: "wellness_seeker",
        },
        createdAt: "2024-10-20T11:15:00Z",
        status: "published",
      },
      {
        id: "seoul-exp-6",
        cityId: "seoul",
        cityName: "Seoul",
        country: "South Korea",
        title: "Seoul Night Life Experience",
        startDate: "2024-11-05",
        endDate: "2024-11-08",
        travelType: "Friends",
        position: "Working",
        participants: "4",
        overallDescription:
          "Epic Seoul nightlife experience with friends. Hongdae clubs, karaoke nights, night markets, and late-night Korean fried chicken. Unforgettable nights!",
        totalCost: 800,
        currency: "USD",
        dailyCost: 50.0,
        duration: 4,
        bookmarkCount: 33,
        isBookmarked: true,
        author: {
          id: "user-31",
          username: "seoul_nightlife",
        },
        createdAt: "2024-11-12T16:50:00Z",
        status: "published",
      },
    ],
  },
  sydney: {
    cityId: "sydney",
    cityName: "Sydney",
    country: "Australia",
    totalCards: 6,
    averageCost: 112.4,
    currency: "USD",
    expenseCards: [
      {
        id: "sydney-exp-1",
        cityId: "sydney",
        cityName: "Sydney",
        country: "Australia",
        title: "Sydney Harbor Romance",
        startDate: "2024-06-18",
        endDate: "2024-06-25",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Romantic week in Sydney exploring the harbor, Opera House, and beautiful beaches. Perfect mix of city attractions and natural beauty.",
        totalCost: 1470,
        currency: "USD",
        dailyCost: 105.0,
        duration: 7,
        bookmarkCount: 22,
        isBookmarked: false,
        author: {
          id: "user-6",
          username: "aussie_adventure",
        },
        createdAt: "2024-07-02T13:25:00Z",
        status: "published",
      },
      {
        id: "sydney-exp-2",
        cityId: "sydney",
        cityName: "Sydney",
        country: "Australia",
        title: "Sydney Beach & Surf Trip",
        startDate: "2024-09-01",
        endDate: "2024-09-08",
        travelType: "Solo",
        position: "Student",
        participants: "1",
        overallDescription:
          "Beach-focused trip to Sydney. Surfing lessons at Bondi, coastal walks, and enjoying the incredible Australian beach culture. Pure bliss!",
        totalCost: 560,
        currency: "USD",
        dailyCost: 80.0,
        duration: 7,
        bookmarkCount: 37,
        isBookmarked: true,
        author: {
          id: "user-32",
          username: "surf_enthusiast",
        },
        createdAt: "2024-09-12T10:40:00Z",
        status: "published",
      },
      {
        id: "sydney-exp-3",
        cityId: "sydney",
        cityName: "Sydney",
        country: "Australia",
        title: "Sydney Family Adventure",
        startDate: "2024-07-22",
        endDate: "2024-07-29",
        travelType: "Family",
        position: "Working",
        participants: "4",
        overallDescription:
          "Family trip to Sydney with kids. Taronga Zoo, Sydney Aquarium, harbor cruises, and beach days. Kids had an amazing time with Australian wildlife!",
        totalCost: 2800,
        currency: "USD",
        dailyCost: 100.0,
        duration: 7,
        bookmarkCount: 25,
        isBookmarked: false,
        author: {
          id: "user-33",
          username: "sydney_family",
        },
        createdAt: "2024-08-05T14:15:00Z",
        status: "published",
      },
      {
        id: "sydney-exp-4",
        cityId: "sydney",
        cityName: "Sydney",
        country: "Australia",
        title: "Sydney Business & Leisure",
        startDate: "2024-10-01",
        endDate: "2024-10-05",
        travelType: "Solo",
        position: "Working",
        participants: "1",
        overallDescription:
          "Business trip to Sydney with leisure time. Professional meetings in the CBD and exploring Sydney's attractions during free time.",
        totalCost: 800,
        currency: "USD",
        dailyCost: 160.0,
        duration: 5,
        bookmarkCount: 12,
        isBookmarked: false,
        author: {
          id: "user-34",
          username: "sydney_business",
        },
        createdAt: "2024-10-10T11:30:00Z",
        status: "published",
      },
      {
        id: "sydney-exp-5",
        cityId: "sydney",
        cityName: "Sydney",
        country: "Australia",
        title: "Sydney Food & Wine Tour",
        startDate: "2024-08-10",
        endDate: "2024-08-15",
        travelType: "Couple",
        position: "Working",
        participants: "2",
        overallDescription:
          "Culinary journey through Sydney. Wine tastings in Hunter Valley, seafood at fish markets, and fine dining with harbor views. Foodie paradise!",
        totalCost: 1400,
        currency: "USD",
        dailyCost: 140.0,
        duration: 5,
        bookmarkCount: 31,
        isBookmarked: true,
        author: {
          id: "user-35",
          username: "sydney_foodie",
        },
        createdAt: "2024-08-20T15:45:00Z",
        status: "published",
      },
      {
        id: "sydney-exp-6",
        cityId: "sydney",
        cityName: "Sydney",
        country: "Australia",
        title: "Sydney Adventure Sports",
        startDate: "2024-11-12",
        endDate: "2024-11-17",
        travelType: "Friends",
        position: "Working",
        participants: "3",
        bookmarkCount: 28,
        isBookmarked: false,
        overallDescription:
          "Action-packed Sydney adventure with friends. Bridge climbing, skydiving, jet boating, and extreme sports. Adrenaline junkies' dream trip!",
        totalCost: 1500,
        currency: "USD",
        dailyCost: 100.0,
        duration: 5,
        author: {
          id: "user-36",
          username: "adventure_seekers",
        },
        createdAt: "2024-11-22T12:10:00Z",
        status: "published",
      },
    ],
  },
};
